---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: prometheus-aws-costs
build: {}
deploy:
  helm:
    releases:
      - name: prometheus-aws-costs
        chartPath: helm/chart
        valuesFiles:
          - helm/chart/values.yaml
        version: 0.1.0
