---
# -- Global values
global:
  # -- Image configuration
  image:
    registry: docker.io
    repository: prometheus-aws-costs
    tag: latest

nameOverride: ""
fullnameOverride: ""

# -- Number of replicas to run
replicaCount: 1

# -- Map of labels applied to all resources
labels: {}

# -- Map of annotations applied to all resources
annotations: {}

# -- Prometheus AWS Costs configuration used as environment variable
config: {}

# -- Configure observability
observability:
  enabled: true
  metricsPort: "11223"
  scrapeInterval: "10m"
  path: "/metrics"

# -- Configure container
container:
  commands:
    - "/go/bin/prometheus-aws-costs"

# -- Node selector for nodes to schedule the pod on
nodeSelector: {}

# -- Tolerations to schedule the pod on tainted nodes
tolerations: []

## -- Node Affinity
nodeAffinity: {}
