---
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::906200835500:role/prometheus-aws-costs-eks-staging-01

config:
  METRIC_INTERVAL: "30s"
  LOG_LEVEL: "debug"
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-agent-collector.telemetry.svc.cluster.local:4317"
