---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "self.common.name" . }}
  labels:
    {{- include "self.common.labels" . | nindent 4 }}
    {{- with $.Values.labels }}
    {{- toYaml . }}
    {{- end }}
  annotations:
    {{- with $.Values.annotations }}
    {{- toYaml . }}
    {{- end }}
data:
    {{- range $k, $v := .Values.config }}
    {{ $k }}: {{ quote (tpl (toString $v) $) }}
    {{- end }}
