---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "self.common.name" . }}
  labels:
    {{- include "self.common.labels" . | nindent 4 }}
    {{- with $.Values.labels }}
    {{- toYaml . }}
    {{- end }}
  annotations:
    {{- with $.Values.annotations }}
    {{- toYaml . }}
    {{- end }}
data:
    {{- if .Values.observability.otel.enabled }}
    OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.observability.otel.endpoint | quote }}
    SERVICE_NAME: {{ include "self.common.name" . | quote }}
    SERVICE_VERSION: {{ .Release.Revision | quote }}
    TELEMETRY_ENABLED: "true"
    {{- end }}
    {{- range $k, $v := .Values.config }}
    {{ $k }}: {{ quote (tpl (toString $v) $) }}
    {{- end }}
