apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pac.common.name" $ }}
  labels:
    {{- include "pac.common.labels" $ | nindent 4 }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: {{ include "pac.common.name" $ }}
  annotations:
    {{- with $.Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: '25%'
      maxSurge: '25%'
  selector:
    matchLabels:
      {{- include "pac.common.matchLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ include "pac.common.name" $ }}
  template:
    metadata:
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pac.common.labels" $ | nindent 8 }}
        {{- with $.Values.labels }}
        {{- toYaml . | nindent 8}}
        {{- end }}
        app.kubernetes.io/component: {{ include "pac.common.name" $ }}
    spec:
      {{- include "pac.pod.securityContext" $ | indent 6 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeAffinity }}
      affinity:
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      containers:
        - name: {{ include "pac.common.name" $ }}
          image: {{ include "pac.container.image"  (dict "name" "global" "context" $) }}
          command: {{- toYaml .Values.container.commands | nindent 12 }}
          {{- with .Values.container.args }}
          args: {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http-metrics
              containerPort: {{ $.Values.observability.metricsPort }}
          envFrom:
          - configMapRef:
              name: {{ include "pac.common.name" . }}
