---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "self.common.name" . }}
  labels:
    {{- include "self.common.labels" . | nindent 4 }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4}}
    {{- end }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- tpl (toYaml .Values.serviceAccount.annotations) . | nindent 4 }}
  {{- end }}
