---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pac.common.name" . }}-service
  labels:
    {{- include "pac.common.labels" . | nindent 4 }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: {{ include "pac.common.name" . }}
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: {{ .Values.observability.metricsPort }}
      targetPort: {{ .Values.observability.metricsPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/component: {{ include "pac.common.name" . }}
